[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
description = "CUDA enabled PyTorch example to deploy in containers"
name = "hello-pytorch"
# non-linux-64 platforms allow for any platform to create the pixi-pack archive
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
start = { depends-on = ["train-mnist"] }

[tasks.detect-gpu]
# c.f. https://gist.github.com/matthewfeickert/a617c83a1bc3b4b2fd33b06bd267de76
description = "Check for a valid GPU and NVIDIA driver setup"
cmd = """
python ./src/torch_detect_GPU.py
"""

[tasks.train-mnist]
description = "Train a simple PyTorch neural net classifier on the MNIST dataset"
cmd = """
python ./src/torch_MNIST.py
"""

[tasks.download-mnist]
description = "Download the MNIST dataset in advance of training"
cmd = """
python -c "\
from torchvision import datasets, transforms; \
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]); \
dataset1 = datasets.MNIST('../data', train=True, download=True, transform=transform)"
"""

# Required for picking up the correct versions of pytorch
# c.f. https://pixi.sh/dev/features/pytorch/#system-requirements
[system-requirements]
cuda = "12"

[target.linux-64.dependencies]
python = "3.13.*"
pytorch-gpu = ">=2.7.1,<3"
cuda-version = "12.9.*"
torchvision = ">=0.22.0,<0.23"

[feature.pack.dependencies]
pixi-pack = ">=0.7.2,<0.8"

[feature.pack.tasks.pack]
description = "Pack the production environment into a pixi-pack archive"
cmd = """
pixi pack --environment prod --platform linux-64 pixi.toml
"""
outputs = ["environment.tar"]

[feature.pack.tasks.pack-executable]
description = "Pack the production environment into self-extracting executable"
cmd = """
pixi pack --environment prod --platform linux-64 --create-executable pixi.toml
"""
outputs = ["environment.sh"]

[feature.pack.target.linux-64.tasks.pack-uuid]
description = "Rename the pixi-pack archive with a UUID based on its hash"
depends-on = ["pack"]
cmd = """
cp environment.tar environment-"$(openssl sha256 -r environment.tar | cut -b -8)".tar
"""

[feature.pack.target.linux-64.tasks.pack-executable-uuid]
description = "Rename the pixi-pack executable with a UUID based on its hash"
depends-on = ["pack-executable"]
cmd = """
cp environment.sh environment-"$(openssl sha256 -r environment.sh | cut -b -8)".sh
"""

[environments]
prod = { features = [], solve-group = "prod" }
pack = { features = ["pack"], no-default-feature = true }
