[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "hello_pytorch"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = { depends-on = ["train-mnist"] }

[tasks.detect-gpu]
# c.f. https://gist.github.com/matthewfeickert/a617c83a1bc3b4b2fd33b06bd267de76
description = "Check for a valid GPU and NVIDIA driver setup"
cmd = """
python ./src/torch_detect_GPU.py
"""

[tasks.train-mnist]
description = "Train a simple PyTorch neural net classifier on the MNIST dataset"
cmd = """
python ./src/torch_MNIST.py
"""

[tasks.download-mnist]
description = "Download the MNIST dataset in advance of training"
cmd = """
python -c "\
from torchvision import datasets, transforms; \
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]); \
dataset1 = datasets.MNIST('../data', train=True, download=True, transform=transform)"
"""

# Required for picking up the correct versions of pytorch
[system-requirements]
cuda = "11"

[dependencies]
python = "3.12.*"
pytorch = ">=2.5.1,<3"
cuda-version = "11.8.*"
torchvision = ">=0.20.1,<0.21"

[environments]
prod = { features = [], solve-group = "prod" }
