[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "hello_pytorch"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
# c.f. https://gist.github.com/matthewfeickert/a617c83a1bc3b4b2fd33b06bd267de76
detect-gpu = """
python ./src/torch_detect_GPU.py
"""

train-mnist = """
python ./src/torch_MNIST.py
"""

start = { depends-on = ["train-mnist"] }

[system-requirements]
cuda = "11"

[dependencies]
python = "3.12.*"
pytorch = ">=2.5.1,<3"
cuda-version = "11.8.*"
torchvision = ">=0.20.1,<0.21"

[environments]
prod = { features = [], solve-group = "prod" }
