universe = container
container_image = oras://ghcr.io/uw-madison-dsi/pixi-docker-chtc:apptainer-hello-pytorch-noble-cuda-12.9

# set the log, error and output files
log = multi_gpu_apptainer_$(Cluster)_$(Process).log.txt
error = multi_gpu_apptainer_$(Cluster)_$(Process).err.txt
output = multi_gpu_apptainer_$(Cluster)_$(Process).out.txt

# set the executable to run
executable = wrapper.sh
arguments = $(Process)

+JobDurationCategory = "Medium"

# transfer training data files and runtime source files to the compute node
transfer_input_files = ../src/

# transfer the serialized trained model back
transfer_output_files = mnist_cnn.pt

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Require a machine with a modern version of the CUDA driver
requirements = (GPUs_DriverVersion >= 12.0)

# We must request 2 CPU in addition to 2 GPU
request_cpus = 2
request_gpus = 2

# select some memory and disk space
request_memory = 2GB
# Apptainer jobs take more disk than Docker jobs for some reason
request_disk = 7GB

# Note that given
# https://github.com/conda-forge/cudnn-feedstock/issues/124
# there can be segfaults for cudnn>=9.11 on pre-Turing devices (<=sm_70)
# so use sm_70 as a safer lower bound
gpus_minimum_capability = 7.0

# Optional: required GPU memory
gpus_minimum_memory = 2GB

# Opt in to using CHTC GPU Lab resources
+WantGPULab = true
# Specify short job type to run more GPUs in parallel
# Can also request "medium" or "long"
+GPUJobLength = "short"

# Environment - HTCondor will set CUDA_VISIBLE_DEVICES automatically
# and _CONDOR_AssignedGPUs will contain the GPU assignments

# Tell HTCondor to run 1 instances of our job:
queue 1
