name: Apptainer Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'examples/hello_pytorch/pixi.toml'
      - 'examples/hello_pytorch/pixi.lock'
      - 'examples/hello_pytorch/apptainer.def'
      - 'examples/hello_pytorch/src/torch_detect_GPU.py'
  pull_request:
    paths:
      - 'examples/hello_pytorch/pixi.toml'
      - 'examples/hello_pytorch/pixi.lock'
      - 'examples/hello_pytorch/apptainer.def'
      - 'examples/hello_pytorch/src/torch_detect_GPU.py'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  apptainer:
    name: Build and publish images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Free disk space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2

      - name: Build container from definition file
        working-directory: ./examples/hello_pytorch
        run: apptainer build pixi-docker-chtc.sif apptainer.def

      - name: Test container
        working-directory: ./examples/hello_pytorch
        run: apptainer test pixi-docker-chtc.sif

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        if: github.event_name != 'pull_request'
        id: meta
        uses: docker/metadata-action@v5
        with:
          # generate container tags based on the following events/attributes
          tags: |
            type=sha

      - name: Deploy built container
        if: github.event_name != 'pull_request'
        working-directory: ./examples/hello_pytorch
        # can't use 'ghcr.io/${{ github.repository }}' as GitHub org is case sensitive
        run: |
          apptainer push pixi-docker-chtc.sif oras://ghcr.io/uw-madison-dsi/pixi-docker-chtc:apptainer-hello-pytorch-noble-cuda-12.9
          # ${{ steps.meta.outputs.tags }} is just the SHA
          apptainer push pixi-docker-chtc.sif oras://ghcr.io/uw-madison-dsi/pixi-docker-chtc:apptainer-${{ steps.meta.outputs.tags }}
