name: Apptainer Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'examples/hello_pytorch/pixi.toml'
      - 'examples/hello_pytorch/pixi.lock'
      - 'examples/hello_pytorch/Dockerfile'
      - 'examples/hello_pytorch/.dockerignore'
      - 'examples/hello_pytorch/src/**'
  pull_request:
    paths:
      - 'examples/hello_pytorch/pixi.toml'
      - 'examples/hello_pytorch/pixi.lock'
      - 'examples/hello_pytorch/Dockerfile'
      - 'examples/hello_pytorch/.dockerignore'
      - 'examples/hello_pytorch/src/**'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  docker:
    name: Build and publish images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Free disk space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2

      - name: Build container from definition file
        working-directory: ./examples/hello_pytorch
        run: apptainer build pixi-docker-chtc.sif apptainer.def

      - name: Test container
        working-directory: ./examples/hello_pytorch
        run: apptainer test pixi-docker-chtc.sif

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy built container
        if: github.event_name != 'pull_request'
        working-directory: ./examples/hello_pytorch
        # can't use 'ghcr.io/${{ github.repository }}' as GitHub org is case sensitive
        run: apptainer push pixi-docker-chtc.sif oras://ghcr.io/uw-madison-dsi/pixi-docker-chtc:hello-pytorch-noble-cuda-12.9-apptainer
